name: CI

# Triggers the workflow on push or pull request
on:
  push:
    branches: [ "features/*" ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Npm install
        run: |
          npm install
          npm run postinstall
        working-directory: ./Sources
      # - name: Compile
      #   run: npm run compile
      #   working-directory: ./Sources
      - name: Pack
        if: ${{ success() }}
        run: npm run pack
        working-directory: ./Sources
      - name: Upload artefact
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: vsix
          path: ./Sources/*.vsix
      # # Publish to the marketplace
      # - name: Publish
      #   run: npm run deploy
      #   env:
      #     VSCE_PAT: ${{ secrets.VSCE_PAT }}